server:
  port: 8081

spring:
  application:
    name: gembackend

  datasource:
    url: jdbc:postgresql://localhost:5434/gem_db
    username: gem
    password: gem123

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true